# Generated by Django 6.0.2 on 2026-03-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtechnician', '0002_alter_labbill_created_at_alter_labbill_final_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborderitem',
            unique_together={('lab_order', 'lab_test')},
        ),
    ]
