# Generated by Django 6.0.2 on 2026-03-05 06:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_user_role_remove_user_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='labtechnicianprofile',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='labtechnicianprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pharmacistprofile',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='pharmacistprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receptionistprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='administration.staffprofile'),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='certification_details',
            field=models.CharField(blank=True, help_text='Optional additional certification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labtech_profile', to='administration.staffprofile'),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to='administration.staffprofile'),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='administration.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='qualification',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist')], default='Doctor', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_code',
            field=models.CharField(db_index=True, default='Doctor', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='license_number',
            field=models.CharField(default='LIC-000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(default='+910000000000', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='salary',
            field=models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
