# Generated by Django 6.0.2 on 2026-03-05 06:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='administration.staffprofile'),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labtech_profile', to='administration.staffprofile'),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to='administration.staffprofile'),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='administration.staffprofile'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist')], max_length=20, null=True),
        ),
    ]
