# Generated by Django 6.0.2 on 2026-03-09 11:59

import django.core.validators
import django.db.models.deletion
import reception.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('consultation_fee', models.PositiveIntegerField()),
                ('daily_patient_limit', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='consultationbill',
            name='amount',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[reception.models.validate_dob]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='reception.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.doctorprofile'),
        ),
    ]
