# Generated by Django 6.0.2 on 2026-03-09 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_doctorprofile_alter_appointment_token_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
