# Generated by Django 6.0.2 on 2026-03-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0002_alter_dispense_dispense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
