# Generated by Django 6.0.2 on 2026-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0003_alter_medicine_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
