# Generated by Django 6.0.2 on 2026-03-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0004_alter_medicinebatch_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenseitem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
